config/routes.rb
Study::Application.routes.draw do
  
  root :to => 'trainings#index'
  
  resources :trainings

  resources :clients

  resources :deals

  resources :companies

  resources :coachings

  resources :trainers

  resources :categories

  resources :places

  resources :towns

end

app/models/training.rb
class Training < ActiveRecord::Base
  attr_accessible :category_id, :company_id, :date, :name, :online, :price, :town_id, :trainer_id
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trainings }
    end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    @training = Training.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(params[:training])

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render json: @training, status: :created, location: @training }
      else
        format.html { render action: "new" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trainings/1
  # PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :online %><br />
    <%= f.check_box :online %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :town_id %><br />
    <%= f.number_field :town_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :trainer_id %><br />
    <%= f.number_field :trainer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<h1>Listing trainings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Online</th>
    <th>Price</th>
    <th>Category</th>
    <th>Town</th>
    <th>Company</th>
    <th>Trainer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trainings.each do |training| %>
  <tr>
    <td><%= training.name %></td>
    <td><%= training.date %></td>
    <td><%= training.online %></td>
    <td><%= training.price %></td>
    <td><%= training.category_id %></td>
    <td><%= training.town_id %></td>
    <td><%= training.company_id %></td>
    <td><%= training.trainer_id %></td>
    <td><%= link_to 'Show', training %></td>
    <td><%= link_to 'Edit', edit_training_path(training) %></td>
    <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @training.name %>
</p>

<p>
  <b>Date:</b>
  <%= @training.date %>
</p>

<p>
  <b>Online:</b>
  <%= @training.online %>
</p>

<p>
  <b>Price:</b>
  <%= @training.price %>
</p>

<p>
  <b>Category:</b>
  <%= @training.category_id %>
</p>

<p>
  <b>Town:</b>
  <%= @training.town_id %>
</p>

<p>
  <b>Company:</b>
  <%= @training.company_id %>
</p>

<p>
  <b>Trainer:</b>
  <%= @training.trainer_id %>
</p>


<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>