config/routes.rb
Study::Application.routes.draw do
  
  root :to => 'trainings#index'
  
  resources :trainings

  resources :clients

  resources :deals

  resources :companies

  resources :coachings

  resources :trainers

  resources :categories

  resources :places

  resources :towns

end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
    @town = Town.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.json
  def new
    @town = Town.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @town }
    end
  end

  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Town was successfully created.' }
        format.json { render json: @town, status: :created, location: @town }
      else
        format.html { render action: "new" }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.json
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to towns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/towns/_form.html.erb
<%= form_for(@town) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render 'form' %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<h1>Listing towns</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @towns.each do |town| %>
  <tr>
    <td><%= town.name %></td>
    <td><%= link_to 'Show', town %></td>
    <td><%= link_to 'Edit', edit_town_path(town) %></td>
    <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>New town</h1>

<%= render 'form' %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @town.name %>
</p>


<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>